### ISSUE TITLE
Proposal: Rename registers to mappings

### ISSUE THREAD

**Issue by LucasKl** [ics-jku/instruction-decoder#13]
The register fields are mostly used to translate from integer values to strings.
While often this is done for registers, sometimes it is not, for example with the RV32 fence instruction.

Renaming registers to mappings makes it maybe more clear that they can be used in other situations as well (e.g., translating a state value to a state name).

**Comment by FRoith** [comment]
yeah, makes a lot of sense, since I changed the way that "registers" work to allow that sort of functionality, renaming them to something like mappings is the play
