### ISSUE TITLE
[Feature Request] RV32 `B` extensions

### ISSUE THREAD

**Issue by hakan-demirli** [ics-jku/instruction-decoder#16]
Recently ratified RV32 `B` extension consist of 4 different extensions: Zbb, Zbs, Zba, Zbc

Details are explained in the latest unprivileged RISCV spec.
https://github.com/riscv/riscv-isa-manual/releases/download/riscv-isa-release-c8c8075-2024-06-12/riscv-unprivileged.pdf

**Comment by hakan-demirli** [comment]
I am not sure how this should be implemented. Zxx extensions are valid on their own. So, each has to be in a separate toml file. However, since there is no `import` mechanism in toml, other files has to be re-defined inside B extension. Ignoring B extension and asking user to specify these 4 extensions explicitly is also an option.

**Comment by LucasKl** [comment]
We are very close to having support for all extensions contained in the official [riscv-opcodes](https://github.com/riscv/riscv-opcodes) repository. Stay tuned :)

**Comment by FRoith** [comment]
Added in the form of separate files, both for RV32 and RV64 variants
