### ISSUE TITLE
[Feature Request] Numeric Registers

### ISSUE THREAD

**Issue by hakan-demirli** [ics-jku/instruction-decoder#21]
In a RISCV design register addresses are 5 bit signals which are (most of the time) assigned to their own separate variable. Surfer does not have a 5 bit register address to register name translator (00001 -> "ra"). Hence, I have to manually look up which decoded instruction does a 5 bit number I have encountered 10 stage down the pipeline corresponds to.

Numeric register support would help quite a lot since `objdump` also supports numeric register names.
![image](https://github.com/ics-jku/instruction-decoder/assets/78746991/7941716c-2628-4810-a446-84863048c1e8)

Straightforward mapping:
```rust
    "zero" -> "x0"
    "ra" -> "x1"
    "sp" -> "x2"
    "gp" -> "x3"
```

**Comment by FRoith** [comment]
that's super easy, all you have to do is change the register list in the toml file to be "x0", "x1"... instead of "zero", "ra"... and it'll do exactly that

**Comment by hakan-demirli** [comment]
Yea, but toml file is embedded inside Surfer and I can not change it after I build it. I was looking for a simple toggle or an entry in right click menu where you can choose to render it either using alias or numeric names. If you are debugging a new custom RISCV core, it is better to use numeric, but if you are debugging an existing design through virtual jtag and gdb it is better to have it in alias mode. I do believe this feature will be really useful for everyone debugging a new/custom core. 

I don't mind patching my tools but we use surfer and gtkwave in a team and we are planning to ditch gtkwave and use surfer exclusively. I hope to keep everything consistent for all since most will use precompiled binaries. However, If this is out of scope of the project or require an overhaul of the codebase I can close the issue.

**Comment by FRoith** [comment]
Ah fair, that makes sense

That's probably more of a surfer issue then, but surfer does now actually allow you to load your own toml files from a config dir, see https://gitlab.com/surfer-project/surfer/-/merge_requests/385

so you could do it that way for now

**Comment by LucasKl** [comment]
My feeling with Surfer's default RISC-V decoders is, that those should be just a convenient way to use quickly. 
If you are working on your own core you probably want to create a config directory with just the supported extensions + your custom instructions. There you can rename the registers. I know renaming them is cumbersome, maybe we can just provide two versions of toml files in this repo.

**Comment by hakan-demirli** [comment]
Yes, custom configs is the right way to approach this issue. Especially if I can create a `.surfer` directory in the repo/project root as requested in  https://gitlab.com/surfer-project/surfer/-/issues/271. I will go ahead and close this issue for 271.
