### ISSUE TITLE
Zcf toml causes parser crash

### ISSUE THREAD

**Issue by georgerennie** [ics-jku/instruction-decoder#28]
Couldn't find much online about what Zcf is meant to look like so wasn't able to fix things, but the following panics due to trying to read a hashmap index that doesn't exist in `display`. https://github.com/ics-jku/instruction-decoder/blob/fb55a1c5c18a68ac59ce8d6af335275a5a9107e5/src/lib.rs#L787

```rust
use instruction_decoder::Decoder;

pub fn main() {
    let decoder = Decoder::new(&vec![include_str!("../toml/RV32_Zcf-lower.toml").to_string()]).unwrap();
    let inst = 0x60026002;
    if let Ok(iform) = decoder.decode_from_i64(inst, 32) {
        println!("{:?}", iform);
    }
}
```

I hit this in surfer which is frustrating because it crashes the whole session - I wonder if it would be possible to more gracefully propagate these errors up.

**Comment by FRoith** [comment]
Zcf is the Float subset of the compressed instructions

just fixed the issue in Zcf, one of the formats there was wrong (fixed it in the commit just now), but before I push it to surfer, I will do some more graceful error handling

**Comment by FRoith** [comment]
and I will keep the issue open until I have the error handling

**Comment by FRoith** [comment]
ok, this should make it so that all things that could cause errors at decoding time will instead cause raise the errors at toml parse time, will merge the changes into surfer asap
